database_connection_string: "host=quests_postgres port=5432 user=adminPG password=1Qwerty2$ dbname=quests sslmode=disable"
http_server:
  address: ":8081"
  timeout_request: 4s # время на чтение запроса и ответ на запрос
  idle_timeout: 60s   # время жизни соединения